name: Build and Deploy to Railway

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build da imagem
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ong-manager:latest .

    - name: Push para o Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ong-manager:latest

  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Instalar Railway CLI
      run: npm install -g @railway/cli

    - name: Conectar no Railway
      env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_DEPLOY_TOKEN }}
      run: railway link -p ${{ secrets.RAILWAY_PROJECT_ID }}
      
    - name: Deploy no Railway
      env:
        RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_DEPLOY_TOKEN }}
      run: railway up
